{% set name = "fps-auth" %}
{% set version = "0.0.33" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fps_auth-{{ version }}.tar.gz
  sha256: 0ebb471e73d1bcb57aff5f42e6f5cc27186a0615d8bc5024334f1b9f3b25c7c5

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - fps >=0.0.8,<1.0.0
    - aiosqlite <1.0.0
    - fastapi-users >=9.1.1,<10
    - fastapi-users-db-sqlalchemy >=1.1.0,<2.0.0
    - httpx-oauth >=0.4,<0.5

test:
  imports:
    - fps_auth

about:
  home: https://github.com/jupyter-server/jupyverse/tree/main/plugins/auth
  summary: An FPS plugin for the authentication API
  keywords: jupyter, server, fastapi, pluggy, plugins
  dev_url: https://github.com/jupyter-server/jupyverse/tree/main/plugins/auth
  license_file: COPYING.md
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - davidbrochart
