{% set name = "fps-auth" %}
{% set version = "0.0.34" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fps_auth-{{ version }}.tar.gz
  sha256: 0a8ede16b68ee864184bda919e16f71b1f44794aa012be64366b8ef84b3ea67c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - fps <1
    - aiosqlite <1
    - fastapi-users >=10.1.4,<11
    - fastapi-users-db-sqlalchemy >=4,<5
    - httpx-oauth <1

test:
  imports:
    - fps_auth

about:
  home: https://github.com/jupyter-server/jupyverse/tree/main/plugins/auth
  summary: An FPS plugin for the authentication API
  keywords: jupyter, server, fastapi, pluggy, plugins
  dev_url: https://github.com/jupyter-server/jupyverse/tree/main/plugins/auth
  license_file: COPYING.md
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - davidbrochart
