{% set name = "fps-auth" %}
{% set version = "0.0.44" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fps_auth-{{ version }}.tar.gz
  sha256: 286dbf4414228f1e632111ee29f78de257372e3f6945a4687b5e420b9478411d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - fps >=0.0.17,<1
    - fps-lab <1
    - fps-uvicorn >=0.0.17,<1
    - fps-login <1
    - aiosqlite <1
    - fastapi-users >=10.1.5,<11
    - fastapi-users-db-sqlalchemy >=4,<5
    - httpx-oauth >=0.4,<0.8
    - httpcore >0.13.3

test:
  imports:
    - fps_auth

about:
  home: https://github.com/jupyter-server/jupyverse/tree/main/plugins/auth
  summary: An FPS plugin for the authentication API
  keywords: jupyter, server, fastapi, pluggy, plugins
  dev_url: https://github.com/jupyter-server/jupyverse/tree/main/plugins/auth
  license_file: COPYING.md
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - davidbrochart
