{% set name = "fps-auth" %}
{% set version = "0.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fps_auth-{{ version }}.tar.gz
  sha256: ca8c10149b4779aae2a9b672b5059a5deb2ae362acd48b0d9c26fd36332e5859

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.8
    - pip
    - hatchling
  run:
    - python >=3.8
    - jupyverse-api >=0.1.4,<1
    - aiosqlite
    - fastapi-users >=13,<14
    - fastapi-users-db-sqlalchemy >=6
    - httpx-oauth >=0.13
    - httpcore >0.13.3

test:
  imports:
    - fps_auth

about:
  home: https://github.com/jupyter-server/jupyverse/tree/main/plugins/auth
  summary: An FPS plugin for the authentication API
  keywords: jupyter, server, fastapi, plugins
  dev_url: https://github.com/jupyter-server/jupyverse/tree/main/plugins/auth
  license_file: COPYING.md
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - davidbrochart
