{% set name = "fps-auth" %}
{% set version = "0.9.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fps_auth-{{ version }}.tar.gz
  sha256: 90272ef140b23ffd607f02e5304694d38b388eeb4b47e50a981a297f83ba5665

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - uv-build
  run:
    - python >={{ python_min }}
    - jupyverse-api >=0.13.0,<0.14.0
    - aiosqlite <0.22.0
    - fastapi-users >=14.0.1,<15.0.0
    - fastapi-users-db-sqlalchemy >=6
    - httpx-oauth >=0.13
    - httpcore >0.13.3

test:
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check
  imports:
    - fps_auth

about:
  home: https://github.com/jupyter-server/jupyverse/tree/main/plugins/auth
  summary: An FPS plugin for the authentication API
  keywords: jupyter, server, fastapi, plugins
  dev_url: https://github.com/jupyter-server/jupyverse/tree/main/plugins/auth
  license_file: COPYING.md
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - davidbrochart
